VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ToolParam"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public pdfHeader As String
Public SelObjColIndex As Integer

Public InputFirstCol As Integer
Public InputLastCol As Integer
Public InputFirstDataRow As Integer
Public InputDataSheetIndex As Integer
Public ResultsSheetIndex As Integer
Public ResultsFirstDataCol As Integer
Public ResultJNIColumn As Integer


Public e As String


